version: "3"
services:
  
  backend:
    container_name: recipes_backend
    restart: always
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    links:
      - mongo

  frontend:
    container_name: recipes_frontend
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
